### ISSUE TITLE
Support multi bower directories?

### ISSUE THREAD

**Issue by Awakening-j** [ck86/main-bower-files#101]
Support multi bower directories?  I will add a bower.json in each extra-lib to be like a bower-managed-lib, so main-bower-files can still work to find `main`
```js
var bowers = gulp.src(mainBowerFiles({
        paths: {
            bowerDirectory: ['bower_components', 'extra-lib']
        },
        "overrides": {
            "bootstrap": {
                "main": [
                    "dist/css/bootstrap.css",
                    "dist/js/bootstrap.js"
                ]
            }
        }
    }), {
        read: false
    });
```

**Comment by TrySound** [comment]
@Awakening-j  https://github.com/ck86/main-bower-files/issues/87

**Comment by Awakening-j** [comment]
@TrySound I mean to add multi paths, not two mainbowerfiles instances, if have two instances, I have to use `require('event-stream').merge`, which cause **memory leak detected** warning.

**Comment by TrySound** [comment]
@Awakening-j Show your gulp case

**Comment by Awakening-j** [comment]
My case is to inject all ['bower_components', 'extra-lib'] to html, and 
```
var bowers = gulp.src(mainBowerFiles(), {
        read: false
    });
```
this works for the bower controlled libs, and I want mainBowerFiles also scan `extra-lib`, the same folder level as bower_components, I've created bower.json for each extra-lib, so how to let mainBowerFiles set multi bowerDirectory?   
![2015-07-28 3 10 04](https://cloud.githubusercontent.com/assets/8085088/8925510/ded3999e-353a-11e5-9123-2b7166dc1dce.png)
![2015-07-28 3 11 52](https://cloud.githubusercontent.com/assets/8085088/8925535/0d6d9390-353b-11e5-8428-5bfacffaebe1.png)

**Comment by TrySound** [comment]
@Awakening-j No way. But main-bower-files returns array. And you can use something like this:
```
gulp.src([].concat(bower(options)).concat(bower(anotherOptions)))
```

**Comment by Awakening-j** [comment]
OK, thanks, wish `Support multi bower directories` can be in next version.  
So at present, I have to `concat(bower({bowerDirectory: 'extra-lib'})` ?

**Comment by TrySound** [comment]
I don't think it could be useful. You can use just arrays with different instances. It's not very difficult.

**Comment by Awakening-j** [comment]
@TrySound Can I ask you some questions about my gulp task? a little complex

**Comment by TrySound** [comment]
Sure

**Comment by Awakening-j** [comment]
@TrySound  thanks. let me summary my questions, I will send you my project

**Comment by Awakening-j** [comment]
@TrySound I've sent you email **trysound@yandex.ru**, thanks very much for your help
