### ISSUE TITLE
Fonts / Glyphicons from "bootstrap-sass-official": "~3.3.4" aren't returned by $.mainBowerFiles()

### ISSUE THREAD

**Issue by crashuniverse** [ck86/main-bower-files#102]
While using `gulp@3.90`, the task `fonts` uses `$.mainBowerFiles()` to get list of all files, but since this doesn't have the list of 5 commonly used bootstrap glyphicons, the build script doesn't copy anything from fonts to `dist/` folder. And this results in no fonts in production.

Fonts task is:

    // Only applies for fonts from bower dependencies
    // Custom fonts are handled by the "other" task
    gulp.task('fonts', function () {
      return gulp.src($.mainBowerFiles())
        .pipe($.filter('**/*.{eot,svg,ttf,woff,woff2}'))
        .pipe($.flatten())
        .pipe(gulp.dest(path.join(conf.paths.dist, '/fonts/')));
    });

**Comment by TrySound** [comment]
@crashuniverse Use native filter
```
gulp.task('fonts', function () {
  return gulp.src($.mainBowerFiles('**/*.{eot,svg,ttf,woff,woff2}'))
    .pipe($.flatten())
    .pipe(gulp.dest(path.join(conf.paths.dist, '/fonts/')));
});
```

**Comment by GDR** [comment]
@TrySound This solution doesn't work.

**Comment by TrySound** [comment]
@GDR Maybe Fonts not in main files. Look at their bower.json and if you'll not find them use overrides option to define what you need.

**Comment by TrySound** [comment]
@GDR This lib just walks through all bower.json deps and returns all found paths. That's all. If something not found, it wasn't there.

**Comment by GDR** [comment]
@TrySound Bootstrap community broke this script. They deleted fonts from "main" in bower files and submitted proposal to bower repo to create special option for bower.json called "Files" where all main deps should be stored. 

They broke everything and didn't offered good solution. :persevere:

**Comment by TrySound** [comment]
@GDR Use [overrides](https://github.com/ck86/main-bower-files#overrides-options) option

**Comment by paulmenzel** [comment]
Quoting the [Bower.json specification](https://github.com/bower/spec/blob/master/json.md#main):

> Image and font files may be used or referenced within the JS or Sass files, but are not main files as they are not entry-points.

So using the override option seems to be the wrong approach to me. But it’s definitely no problem with main-bower-files.

Though, I’m curious in the best practices for dealing with font files.

PS: It’s unfortunate, that this [change](https://github.com/twbs/bootstrap-sass/pull/898) was done in a patch version from 3.3.4 to 3.3.5.
