### ISSUE TITLE
gulp.dest on an folder containing the base does not copy anything

### ISSUE THREAD

**Issue by bennekrouf** [ck86/main-bower-files#105]
Do you know why :

<code>
   gulp.task('bowerDep', function(){
     return gulp.src(bowerFiles(), {base: 'libs'})
           .pipe(gulp.dest('.dist/libs'));
   });
</code>

does not copy anything.

while :

<code>
gulp.task('bowerDep', function(){
  return gulp.src(bowerFiles(), {base: 'libs'})
        .pipe(gulp.dest('.dist/toto'));
});
</code>

works  ???

With 'toto' or any other word that 'libs' (my base one).

**Comment by TrySound** [comment]
@bennekrouf It's not main-bower-files. Read more about gulp and base.

**Comment by bennekrouf** [comment]
It does not help me a lot.

**Comment by TrySound** [comment]
@bennekrouf I don't know too what's problem. For me it works fine.
