### ISSUE TITLE
ignoring changes to "main" in bower.json's

### ISSUE THREAD

**Issue by dkebler** [ck86/main-bower-files#106]
After much fussing I can only think my issue is something wonky in main-bower files.

I have a bower package I loaded (hover).  It's "main" file points to a css file.  The packages also includes an scss version but the author did not include that in his "main".  But when I change "main" main-bower-files ignores the change still reporting the original.  In fact not matter what I change it to main-bower files doesn't see it only the original one.  If I change bower.json in some other package it's the same deal.  The debug still indicates nothing has changed in the "main".

So bottom line is main-bower-files works on first pass through bower_components but then ignores any changes to each bower.json thereafter

Any thoughts?

debug shows only one main file for hover (hover.css)
```
Package           overriding main         jeet              ["stylus/jeet/index.styl","scss/jeet/index.scss"]
PackageCollection add                     hover             /mnt/AllData/hacking/hugo-sass-bower-gulp-starter/bower_components/hover
Package           overriding main         hover             css/hover.css
Package           select file             hover             /mnt/AllData/hacking/hugo-sass-bower-gulp-starter/bower_components/hover/css/hover.css
````

even though json file has two main files.

```json
{
  "name": "hover",
  "version": "2.0.2",
  "homepage": "http://ianlunn.github.io/Hover",
  "authors": [
    "Ian Lunn <hello@ianlunn.co.uk>"
  ],
  "description": "e in CSS, Sass, and LESS",
    "main": [
    "css/hover.css",
    "scss/hover.scss"
  ],
  "keywords": [
    "Hover",
    "hover",
    "hover.css",
    "Hover Effects",
    "CSS Effects",
    "CSS3 Effects",
    "CSS Hover Effects",
    "CSS3 Hover Effects"
  ],
  "license": "MIT",
  "private": false,
  "ignore": [
    "**/.*",
    "node_modules",
    "bower_components",
    "test",
    "tests"
  ]
}
```
here is my gulp task code which calls main-bower-files.

```js
// loads up the paths for scss files in bower packages
gulp.task('sass-bower', function () {

var path  = require('path');
var sassBower  = require('main-bower-files');
var json = require('json-file');

var rcfile = path.resolve('.bowerrc');
// console.log('bower rc:' + rcfile);
 
// Load a JSON file 
var bowerrc = json.read(rcfile);

// console.log('bower directory:' + bowerrc.get('directory'));
// console.log('sass paths before: ' + bowerrc.get('scss_paths'));

var base_path = path.resolve(bowerrc.get('directory'));
//   console.log('base_path:' + base_path); 

// grab all the full paths, package MUST appear in bower.json so use --save-dev option when installing
var scss_paths = sassBower({
  base: base_path,
  filter: ['**/_*.scss','**/*.scss'],
  debugging: true,
  includeDev: true
  
});

console.log('number of scss "main" files found' + scss_paths.length); 

var scss_paths_log ='';
for (var i=0; i<scss_paths.length; i++){
  scss_paths_log = scss_paths_log + scss_paths[i] + '\n';
// libsass wants only the parent directory of each "main" file so remove the filenames
  scss_paths[i] = path.dirname(scss_paths[i]);
}  

console.log('scss_paths:' + scss_paths_log ); 

bowerrc.set('scss_paths', scss_paths);
bowerrc.writeSync();

});
```

**Comment by dkebler** [comment]
just a followup.  I tried this.  uninstalled hover.  Ran my sass-bower task.  Indeed main-bower-files debug shows it's gone.  Now reinstall hover.  Edit the json file immediately to change to `"main": ["scss/hover.css","css/hover.css"]`, run sass-bower task but main-bower-files STILL says

`PackageCollection add                     hover             /mnt/AllData/hacking/hugo-sass-bower-gulp-starter/bower_components/hover
Package           overriding main         hover             css/hover.css
`
so somehow they way I am calling main-bower-files keeps returning some "old call" that is still in cached in memory????

**Comment by ck86** [comment]
Hey @dkebler,

I can not reproduce your issue. You should override the main property in _your_ bower.json file, not directly in the packages bower.json file. Here is my bower.json example:

```json
{
  "dependencies": {
    "hover": "~2.0.2"
  },
  "overrides": {
    "hover": {
      "main": [
        "css/hover.css",
        "scss/hover.scss"
      ]
    }
  }
}
```

And if I run this small js:

```js
console.log(require('main-bower-files')({
	debugging: true
}))
```

I get this output:

```bash
PackageCollection add                     hover             /Users/cknoetschke/Downloads/tmp/bower_components/hover
Package           select file             hover             /Users/cknoetschke/Downloads/tmp/bower_components/hover/css/hover.css
Package           select file             hover             /Users/cknoetschke/Downloads/tmp/bower_components/hover/scss/hover.scss
```

**Comment by dkebler** [comment]
Thx!

Using overrides (which I was not aware of) worked as you suggested.


But it is a bit puzzling to me why any edits I make to actual package's
bower.jsons are ignored??

Can main-bower-files tell that a package bower.json as been changed from
the original repo and thus ignore those changes???

Would appreciate an explanation of the main-bower-files logic in this
regard since it seems unexpected behaviour (at least to me).

For example what if I create my own "package" not actually loaded via
bower?  Would main-bower-files ignore my main settings?

On Mon, Aug 10, 2015 at 1:52 AM, Christopher Knötschke <
notifications@github.com> wrote:

> Hey @dkebler <https://github.com/dkebler>,
>
> I can not reproduce your issue. You should override the main property in
> *your* bower.json file, not directly in the packages bower.json file.
> Here is my bower.json example:
>
> {
>   "dependencies": {
>     "hover": "~2.0.2"
>   },
>   "overrides": {
>     "hover": {
>       "main": [
>         "css/hover.css",
>         "scss/hover.scss"
>       ]
>     }
>   }
> }
>
> And if I run this small js:
>
> console.log(require('main-bower-files')({
>     debugging: true
> }))
>
> I get this output:
>
> PackageCollection add                     hover             /Users/cknoetschke/Downloads/tmp/bower_components/hover
> Package           select file             hover             /Users/cknoetschke/Downloads/tmp/bower_components/hover/css/hover.css
> Package           select file             hover             /Users/cknoetschke/Downloads/tmp/bower_components/hover/scss/hover.scss
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ck86/main-bower-files/issues/106#issuecomment-129369886>
> .
>



-- 
Cheers, Cuidate, TTFN <http://www.youtube.com/watch?v=5Gu50vq5ux4>
David

**Comment by ck86** [comment]
main-bower-files looks for the following files in that order: `.bower.json`, `bower.json`, `package.json` and `component.json`.

And bower always creates a `.bower.json` even if the package does not have a `bower.json`.

**Comment by ck86** [comment]
And I would not recommend to edit those files directly because your have to do that always again if you re-install or update the packages.
