### ISSUE TITLE
Using with grunt: file list in dependency order?

### ISSUE THREAD

**Issue by danielbsig** [ck86/main-bower-files#107]
Hi,

I've been using this module with gulp for some time now, and I'm very pleased with it. I've also got another project which uses grunt, and would like to use main-bower-files there as well. However, I can't figure out how to use this module in grunt, especially when I need to generate a list of script files to be included in my index.html, since they must be added in a particular order (for instance, jquery.js must be included before angular.js, and angular.js before all the 3rd party angular modules etc.).

Does anyone know how to achieve this?

Regards,
Daníel

**Comment by ck86** [comment]
Hi @danielbsig,

main-bower-files should return an ordered list of files and you could do something like this:

```js
{
  'your-grunt-task': {
    files: {
      src: mainBowerFiles('**/*.js')
    }
  }
}
```
