### ISSUE TITLE
how to pick bower lib by whitelist

### ISSUE THREAD

**Issue by Awakening-j** [ck86/main-bower-files#108]
Assume I write a config file to list all the lib for each html file, so how to let `mainbowerfiles` filter it.  
```javascript
var config = [{
    'index.html': [jquery, underscore],
    'dashboard.html': [jquery, bootstrap]
}];
```
```
gulp.task('test', () => {
    return gulp.src(mainBowerFiles({list: [jquery, underscore]}))
        .pipe(gulp.dest('.tmp/test/'));
})
```  
So the work flow: filter by list -> find libs in bower_components -> read 'main' in bower.json -> get required files from mainBowerFiles,  
Can this happen in any gulp plugin? or in next version of bowermainfiles?  
I know at present, bowermainfiles has filter, but not filter bower-name, it get all files declared in 'main'

**Comment by ck86** [comment]
Why not using the filter?

```js
mainBowerFiles({
  filter: /(jquery|underscore)\//
});
```

**Comment by TrySound** [comment]
@ck86 Or ;)
```
mainBowerFiles(/(jquery|underscore)\//);
```

**Comment by ck86** [comment]
@TrySound nope, currently the first argument will be set as the filter if it is a type of string or array ;)

but we should add a check for regex ...

**Comment by TrySound** [comment]
@ck86 Oops. Okay :)

**Comment by TrySound** [comment]
@ck86 Path or minor?

**Comment by ck86** [comment]
I think it's a feature, so it would be minor from my side.

**Comment by Awakening-j** [comment]
@ck86 @TrySound I've thought about filter, but you know that, the bower main files may not named start with the bower lib name.   
for example:  
bower: jquery
main: jquery.js  
but ......  
bower: blueimp-md5
main: md5.js  

So filter main files may not exact, filter bower lib name may be better :)

**Comment by ck86** [comment]
main-bower-files returns an array of files where each file is an absolute path and that array will be filtered by the filter option. If your project lives in `/foo/bar` and your bower packages are `bower_components` you would get something like this:

/foo/bar/bower_components/jquery/jquery.js
/foo/bar/bower_components/blueimp-md5/md5.js

So you always have the package name in the paths.

**Comment by Awakening-j** [comment]
ok, thanks

**Comment by JordyPouw** [comment]
I'm trying to filter my packages, but it doesn't filter at all. Also tried it with the 'filter: ....' syntax.
I first thought of a version issue, but when I filter on '**/*.css' it works. But I can't seem to filter the packages..

Any ideas?

`
     var vendorLibs = /(jquery|underscore)\//;
     gulp.src('bower.json')
       .pipe(config.plugins.plumber())
       .pipe(config.plugins.bower(vendorLibs, {
         overrides: {}
       }))
      .pipe(...........
`
