### ISSUE TITLE
Glob match not working after 2.9 update

### ISSUE THREAD

**Issue by limoragni** [ck86/main-bower-files#110]
Hey! I had this line `mainBowerFiles(['**/*polyglot.js','**/*jquery.js'])` working Ok on my app. But after updating to 2.9 it sopped working. Any idea why?

**Comment by foustleague** [comment]
Try it

```
mainBowerFiles({
  filter: ['**/polyglot.js', '**/jquery.js']
})
```

**Comment by ck86** [comment]
Which version did you had before?

**Comment by foustleague** [comment]
I'm using 2.9

**Comment by limoragni** [comment]
Ok, great. I'm sorry, I don't think it was really a problem with the version. I installed my environment into another machine and I thought that was the problem, but it seems to be Jenkins messing with the paths or something like that. @foustleague thanks for the filter tip, it seem much more clean that my version. I'm going to try that out.

**Comment by ck86** [comment]
Can be closed?

**Comment by foustleague** [comment]
I believe so
