### ISSUE TITLE
base not working?

### ISSUE THREAD

**Issue by ethanclevenger91** [ck86/main-bower-files#113]
I've got:

```
return gulp.src(bowerFiles('**/*.css'), {base: paths.bowerDir})
.pipe(...);
```

Where `paths.bowerDir` is `../../bower_components`. However, I'm still getting an error "Bower components directory does not exist at..." followed by my cwd with `bower_components` appended. I feel like there's probably something I just don't understand. Thoughts?

**Comment by TrySound** [comment]
https://github.com/ck86/main-bower-files#paths
