### ISSUE TITLE
Individual destination directory for files

### ISSUE THREAD

**Issue by alexanderkatkov** [ck86/main-bower-files#115]
Hi.
I'm using gulp.
I need to take main files from bower components folder & copy each file to unique folder.

Example:
We have jquery.min.js, normalize.css, remodal.min.js, remodal.css, remodal.theme.css in bower components as main files.

I need to copy jquery to demo/js folder. remodal.js to js/components/remodal folder, normalize.css to less/components/normalize folder and all remodal css to less/components/remodal folder.

Is it posible somehow to assign destination folder to each file?

Thanks for responce.

**Comment by TrySound** [comment]
https://github.com/ck86/main-bower-files/issues/62#issuecomment-142867438

**Comment by alexanderkatkov** [comment]
ok. Thanks.
Can you tell me one more thing: what will return to me gulp.src( mainBowerFiles() ),
object with names & paths ?

**Comment by ck86** [comment]
Array with paths

**Comment by alexanderkatkov** [comment]
ok. Thank you. Thats all)

**Comment by ck86** [comment]
but for your problem you could use https://www.npmjs.com/package/gulp-rename
