### ISSUE TITLE
Fallback to 'development' main files when not found

### ISSUE THREAD

**Issue by ProLoser** [ck86/main-bower-files#118]
Could it be possible to have some sort of 'fallback' main file when the specific override isn't found? I have several different environments, and all but production are identical, but if I override the configuration I have to explicitly enumerate the files for each and every environment which is very tedious (since production needs to use the min version of these projects).

**Comment by TrySound** [comment]
@ProLoser You can add overrides with both types of files and filter in dev ['**/*.js', '!**/*.min.js'] and in prod ['**/*.min.js']

**Comment by ProLoser** [comment]
I'm saying if you have other environments such as staging, testing, etc, then I have to explicitly define those overrides too. This has nothing to do with search filtering.

**Comment by TrySound** [comment]
@ProLoser What do you want? This module just walk all bower.json dependencies and collect main field paths. Nothing more.
