### ISSUE TITLE
.bowerrc - If it exists but is empty you will error

### ISSUE THREAD

**Issue by embrasse-moi** [ck86/main-bower-files#119]
I had deleted my bower_component install path out of .bowerrc, but left the file. Figured it would be fine.
 This will generate the error
SyntaxError: Unexpected end of input 
at
main-bower-files/lib/index.js:48:43

Deleting .bowerrc fixes the error

**Comment by TrySound** [comment]
Show `.bowerrc`

**Comment by embrasse-moi** [comment]
.bowerrc was totally empty.

**Comment by TrySound** [comment]
@embrasse-moi Error means unexpected json. And bower.json and .bowerrc should be correct json. At least empty object `{}`
