### ISSUE TITLE
Error when attempting to set a basepath

### ISSUE THREAD

**Issue by greg5green** [ck86/main-bower-files#12]
When invoking with a basepath

```
mainBowerFiles({ paths: 'path/for/project' });
```

an error is thrown:

```
Error: bower.json file does not exist at undefined
```

Maybe an older version of Node allowed you to set properties to strings, but it doesn't seem to be allowed in v0.10.28.

**Comment by daveteply** [comment]
This is #12

**Comment by ck86** [comment]
You're right, but this issue is one year old, so I can't remember anymore. :D

**Comment by daveteply** [comment]
Sorry! :)  I was experiencing a similar issue but I got it figured out in my gulpfile.js:
```javascript
var bowerFiles = require('main-bower-files');
...
var bower = gulp.src(bowerFiles({ paths: './dev-app' }), { read: false });
```
Thank you!
