### ISSUE TITLE
Is it possible to put `main` files to one folder ?

### ISSUE THREAD

**Issue by athimannil** [ck86/main-bower-files#121]
Is it possible to copy `.js` files to one specific `javascript` folder with **gulp** plugin `main-bower-files ` ?

    var gulp = require('gulp'),
        bower = require('gulp-bower'),
    	mainBowerFiles = require('gulp-main-bower-files'),
    gulp.task('mainbower', function() {
        return gulp.src('./bower.json')
            // .pipe(mainBowerFiles([[filter, ]options][, callback]))
            .pipe(mainBowerFiles())
            .pipe(gulp.dest('./wwwroot/libs'));
    });

Here is the current folder copying result as separate folder with the plugin 👇 

<img width="238" alt="screen shot 2015-10-31 at 4 02 45 pm" src="https://cloud.githubusercontent.com/assets/4364227/10863489/df37b5a2-7fe8-11e5-9986-7214ce238d81.png">

**Comment by TrySound** [comment]
@athimannil Do not use `gulp-main-bower-files` it's deprecated caz wrapper is useless. `main-bower-files` returns only list of files which can be passed to `gulp.src()`. To squash directories tree u can use https://github.com/armed/gulp-flatten
