### ISSUE TITLE
Copy routine stops if bower.json file contains no "main" entry

### ISSUE THREAD

**Issue by GeroL** [ck86/main-bower-files#124]
Test package: polymer-starter-kit
It contains no main entry. No dependencies are copied. 
If I insert an empty main entry manually all dependencies are copied.

**Comment by ck86** [comment]
@GeroL There is no bower package "polymer-starter-kit".

**Comment by GeroL** [comment]
Ah sorry it's "PolymerElements/polymer-starter-kit"

**Comment by ck86** [comment]
The problem is that main-bower-files reads .bower.json, bower.json, package.json and composer.json until one file has a main property. In case polymer-starter-kit it uses the last found file which is package.json which has no dependencies.
