### ISSUE TITLE
cannot load ngCordova from mainbowerfiles

### ISSUE THREAD

**Issue by wwpra** [ck86/main-bower-files#126]
I have problem while building an app with gulp. when I built the code, I found that ngCordova is missing from the index.html. The other bower components were injected successfully. 

to check, I created simple gulp task to list all bower components.
```javascript
gulp.task('bower-check', function() {
return gulp.src($.mainBowerFiles(), {
            base: 'bower_components'
        })
        .on('end', function() {
            $.util.log($.mainBowerFiles());
        });
});
```
but when I ran the task, I found that **ngCordova** component is missing. (which probably is the root of the problem)

![image](https://cloud.githubusercontent.com/assets/5959662/12119754/fedcafe8-b3ff-11e5-9506-e63004b29832.png)

I have tried several way i.e.
- update npm, gulp, bower with the latest version
- start from clean installation and run `npm install` and `bower install`
- make sure that **ngCordova** is in **bower_components** folder, and yes it is there.
![image](https://cloud.githubusercontent.com/assets/5959662/12120108/d823c178-b401-11e5-90c6-be7145fd6708.png)

I have tried some other unmentionable ways , but still, couldn't resolve why **ngCordova** cannot be injected. Seems that `mainBowerFiles()` function unable to load it. why? please advise.

**Comment by ck86** [comment]
Is the ngCordova dependency listet in your bower's dependencies?

**Comment by wwpra** [comment]
yes, here's the bower.json at my app root folder:

![image](https://cloud.githubusercontent.com/assets/5959662/12131439/22b7d952-b445-11e5-863b-82791147c50c.png)

**Comment by ck86** [comment]
https://gist.github.com/ck86/12501983b4099d7dd620

I have no clue what's going wrong, may be a case sensitive issue on windows?

**Comment by wwpra** [comment]
HI @ck86 , I test your script, below is the result
![image](https://cloud.githubusercontent.com/assets/5959662/12140488/f4b642fe-b49a-11e5-8d9d-c75deb8c8048.png)

I'm not sure, why the angular-ui-router and ngCordova is missing from the select file ?

I'm using windows 8.1 pro 64bit, node 5.3.0, npm 3.5.2

**Comment by ck86** [comment]
Can you run main-bower-files with `checkExistence` ?

**Comment by wwpra** [comment]
:100: I ran the script again with `checkExistence`. found the js file was missing 

![image](https://cloud.githubusercontent.com/assets/5959662/12173840/b353a666-b58b-11e5-8a3f-6a02d893e0c9.png)

I only checked that the folder existed, didn't see that the js file was not created, must be a problem with my bower installation, gotta check that :). Thanks a lot @ck86
