### ISSUE TITLE
How to get css files as well?

### ISSUE THREAD

**Issue by MrSkinny** [ck86/main-bower-files#127]
Sorry I know this is probably not specific to this tool, but I'm using gulp in my project and want to concat/minify all my bower components.  When I use the default `mainBowerFiles()` in gulp it only finds the js and not the css (I understand it's collecting the "main" key in `bower.json`.

What's a best practice to also acquire all the CSS files in each bower component -- I know how to minify/concat etc but wondering what I'm missing in why `main-bower-files` wouldn't also be automated to grab the css content as well...?

**Comment by TrySound** [comment]
```js
mainBowerFiles('**/*.css');
```

**Comment by MrSkinny** [comment]
Thanks @TrySound, didn't realize the rather obvious option to override by passing a glob in

**Comment by ck86** [comment]
@MrSkinny passing a glob just filters the result. You have to [override[(https://github.com/ck86/main-bower-files#main) the main files in your own bower.json.

**Comment by MrSkinny** [comment]
@ck86 Thanks.  I overrode the main with `"**/*"` and then used different filter calls for my gulp js and css tasks. Is that the intended usage?

**Comment by ck86** [comment]
Not really, I recommend to add only those files, which you want to use. If you work together with other developer, they might not know which files you are actually using. He/She have to look in your gulp task.

**Comment by MrSkinny** [comment]
Got it, used array instead to just grab js and css. Thx for the help

**Comment by AlexanderKozhevin** [comment]
So, how does you solution look like?
I'm having a similar problem. In most libraries with good bower file, css files are exported. But with other packages only **.js** files are exported.

**Comment by AlexanderKozhevin** [comment]
This task finds only css files  mentioned in bower file. 
```
var mainBowerFiles = require('main-bower-files');
gulp.task('assetscss', function() {
    return gulp.src(mainBowerFiles("**/*.css"), { base: 'bower_components' })
      .pipe(gulp.dest('production/css'))
});
```

**Comment by ck86** [comment]
You can't really automate. If one file is missing, you can override the `main` property of the package in your own bower.json.

**Comment by MrSkinny** [comment]
@AlexanderKozhevin this might go against the intention of main-bower, but I have this in bower.json to capture all the js/css:
```
  "overrides": {
    "bootstrap-notify": {
      "main": ["**/*.js", "**/*.css"]
    }
```

Then in gulpfile I have:

```
// Bower css
gulp.task('lib-styles', function(){
  gulp.src(mainBowerFiles("**/*.css"))
   .pipe(concat('lib-styles.css'))
   .pipe(minifyCss())
   .pipe(gulp.dest(config.paths.DIST_PATH))
});

// Bower js
gulp.task('lib-scripts', function(){
  gulp.src(mainBowerFiles("**/*.js"))
    .pipe(uglify())
    .pipe(concat('lib-scripts.js'))
    .pipe(gulp.dest(config.paths.DIST_PATH))
});

```
using the filter arg to grab the css and js separately

**Comment by AlexanderKozhevin** [comment]
Thanx. 
I decided to create array of files which are not mentioned in **main** in bower. 
Btw, I prefer to use uglify as a separate gulp command, when your front-end ready for deploy. 
It takes some time to uglify project which includes more than 25 packages:)
