### ISSUE TITLE
Add a "relative" option

### ISSUE THREAD

**Issue by pierrecle** [ck86/main-bower-files#128]
It would be nice to have an option to get files path relative to another path.
For example, in my use [in bdlr](https://github.com/pierrecle/bdlr), I create bundles which render the html tags for their files. It needs to be relative to a directories, to be correctly served by a server. It would prevent to post-process the paths given by `main-bower-files` as I had to do [here](https://github.com/pierrecle/bdlr/blob/master/src/Bundle.js#L73).

My proposal is to add a `relative` option with the following behavior:
- if `true` is given, relative to the main `bower.json` directory path; ie `process.cwd()` or `path.dirname(require.main.filename)` 
- if a path is given, relative to that path
- if not set, leave absolute

**Comment by marcin-wosinek** [comment]
It's doable with [bower-files](https://www.npmjs.com/package/bower-files):

```
var bowerFiles = require('bower-files')();
var files = bowerFiles.ext().relative(__dirname).files;
```
