### ISSUE TITLE
Why the change in syntax?

### ISSUE THREAD

**Issue by 4tron** [ck86/main-bower-files#130]
I am not sure if i am doing something wrong or what but , as far as i can recall the syntax for mainbowerfiles was

    mainBowerFiles({
          filter: '**/**/*.js',
          includeDev:true
    })

This was working until today when i got the latest version. This is now breaking and according to your documentation the "new" ( if it is new, i dont remember reading the docs )

      mainBowerFiles([[filter] options ]))

I have tried this

     mainBowerFiles([['**/**/*.css'], {includeDev:true} ]))

but am getting a `SyntaxError: Unexpected token } ` . Im a bit lost at how to implement this. 

      mainBowerFiles([['**/**/*.css'], includeDev:true ])) // This will obviously not work.
      mainBowerFiles([['**/**/*.css'] includeDev:true ])) // Nor will this
      mainBowerFiles([['**/**/*.css'] "includeDev" = true ])) // Nor will this

feeling like a proper noob here.

**Comment by ck86** [comment]
the square brackets means that the params are optional and not an array.

your example should be look like this:

```js
mainBowerFiles('**/**/*.css', {includeDev:true})
```

**Comment by 4tron** [comment]
There was a problem in the yeoman generator not downloading the bower files . there are no bower files to move . Sorry for the time waste
