### ISSUE TITLE
Group as array

### ISSUE THREAD

**Issue by leocaseiro** [ck86/main-bower-files#132]
That would be nice if the option group were an array, so I could combine 2 or more groups in one only.

Example:

```javascript
"group": {
    "core": ["angular"],
    "map": ["angular-google-maps"],
    "bootstrap": ["angular-bootstrap", "font-awesome"],
}
```

So I could use, like:
```javascript
mainBowerFiles({group: ['core', 'map', 'bootstrap']});
```

PS: My scenario is to deploy only a part of my app for each section.

**Comment by nathanaelnsmith** [comment]
I could probably take a crack at this since I was just in that method
