### ISSUE TITLE
not all files are included in some packages

### ISSUE THREAD

**Issue by kfirufk** [ck86/main-bower-files#134]
Hi.

I have two bower packages that mainBowerFiles() doesn't include  all of their files.

1. angular-datatables
    it doesn't include the minified version of the js (bower_components/angular-datatables/dist/angular-datatables.min.js)
2. base64-js
   it doesn't include the main js file (bower_components/base64-js/base64js.min.js)

did i miss a configuration option or something ?

**Comment by TrySound** [comment]
@kfirufk 1. bower packages shouldn't include minified files. 2. Main package doesn't have main field in bower.json. You can use overrides for this case.
