### ISSUE TITLE
Bower files with no dependencies are placed at higher position

### ISSUE THREAD

**Issue by sendilkumarn** [ck86/main-bower-files#136]
@ck86  Consider libs like angular-cache-buster since they have no dependencies added to it, which makes them come before angular js definition. Any hacks ?

**Comment by ck86** [comment]
There are 2 options:
1. you can simply move angular-cache-buster before angularjs.
2. you can override the angular-cache-buster's dependencies as you would do it for main files and add angularjs

**Comment by sendilkumarn** [comment]
The problem is that whenever I add more libraries, then I end up in manually updating them. 

Can we do any of these ?

1. adding jquery and angular js as initial dependency and then ordering based on priority
2. check for angular.module also as one of the dependency check?

**Comment by ck86** [comment]
Nope, this is "too dirty". If you would add angularjs as an dependency to angular-cache-buster, you don't need to update everything if you add packages.

**Comment by deepu105** [comment]
@sendilkumarn I think what @ck86 suggested is to add the below to the bower file 
```
"overrides": {
    "angular" : {
      "dependencies": {
        "jquery": "2.2.2"
      }
    },
    "angular-cache-buster": {
      "dependencies": {
        "angular": "*"
      }
    }, so on
  },
```
