### ISSUE TITLE
How can I get all files not in a specific group

### ISSUE THREAD

**Issue by goodforenergy** [ck86/main-bower-files#138]
Hey there,

I have a group of modules in my bower file that are to be loaded in older browsers only (shims etc). I can use `mainBowerFiles({ paths: 'path/for/project', group: 'oldie' })` to get only these files, but without explicitly listing their names in a filter function, how can I get the rest of the files with none from group `oldie`? Is there a way of getting hold of registered groups?

Thanks!

Helen

**Comment by nathanaelnsmith** [comment]
I've created a fix for this on a fork, but I'm new to contributing so I don't know the protocol to follow to get my change pulled in

**Comment by goodforenergy** [comment]
@nathanaelnsmith awesome, thanks for your work! Eagerly awaiting the merge.
