### ISSUE TITLE
base option not being used

### ISSUE THREAD

**Issue by jdglanville** [ck86/main-bower-files#142]
The "You've got a flat folder/file structure..." section on the front page describes how and when to use the `base` option. However, it appears this option isn't actually being used. When using this option, I'm still getting a flat file structure.

I had a quick look at the source code. I can see where the `opts.base` value is being set (`index.js`, line 85). However, I can't see where this value is being used.

Finally, I think there's a minor error with the documentation for `base` on the front page. There's the line:

> `return gulp.src(mainBowerFiles(/* options */), { base: 'path/to/bower_components' })`

I think this should be:

> `return gulp.src(mainBowerFiles(/* options */  { base: 'path/to/bower_components' }))`

**Comment by ck86** [comment]
The base option is not part of main-bower-files. It is part of gulp.src and should be passed as the second parameter.

**Comment by jdglanville** [comment]
Yup. I realized the same thing as you're typing out your reply. Problem defiantly between keyboard and chair.

Before I close this (non-existent) issue, is there an `opts.base`? As previously noted, I see a reference to `base` in the `index.js` file, but I never see it used. Is this line superfluous, or is this another example of the lack of understanding in the space between keyboard and chair?

**Comment by ck86** [comment]
Seems to be obsolete. I check it in more detail asap. :)
