### ISSUE TITLE
Doesn't work with jssocials jQuery plugin

### ISSUE THREAD

**Issue by matjazmav** [ck86/main-bower-files#148]
I can't get **jssocials** ([GitHub](https://github.com/tabalinas/jssocials)) to work with `gulp` and `main-bower-files` plugin. I have checked `bower.json` all main files are there, but for some reason they doesn't get in the pipe.

This is snippet from my `gulpfile.js`:
```js
var gulp = require('gulp'),
    bower = require('main-bower-files'),
    concat = require('gulp-concat'),
    uglify = require('gulp-uglify'),
    plumber = require('gulp-plumber');

gulp.task('js', [], () => {
    var src = bower(['**/*.js']).concat([
        // Add custom files
    ]);
    return gulp.src(src)
        .pipe(plumber())
        .pipe(uglify())
        .pipe(concat('all.min.js'))
        .pipe(gulp.dest('dist/assets/js'));
});
```

I'm also using other libraries that work great with this approach.

Am I missing something?
Thanks

**Comment by ck86** [comment]
Is it possible that you miss jssocials as a dependency in your own bower.json?

**Comment by matjazmav** [comment]
Oh yes :) thank you, how could I missed it... :)
