### ISSUE TITLE
Strange work with npm_modules folder

### ISSUE THREAD

**Issue by amorphine** [ck86/main-bower-files#149]
I try to get main files of bxslider. main-bower-files works fine with bower_componets/ but if I tty to get files from npm_modules I get only jquery.js (it is a dependcy of bxslider).
My task simplified

```
gulp.task('bxslider', function(){
    var bower = mainBowerFiles({
        paths: {
            bowerDirectory: 'node_modules',
            bowerJson: './node_modules/bxslider/bower.json'
        },
    });
    return gulp.src(bower)
        .pipe(gulp.dest('assets/dist/bxlider'));
});
```

Here it is a bxlider/bower.json
```

{
  "name": "bxslider-4",
  "version": "4.2.5",
  "homepage": "http://bxslider.com",
  "license": "MIT",
  "main": [
    "dist/jquery.bxslider.js",
    "dist/jquery.bxslider.css",
    "dist/images/bx_loader.gif",
    "dist/images/controls.png"
  ],
  "ignore": [
    "docs_src/*",
    "docs/*"
  ],
  "keywords": [
    "bxslider",
    "javascript",
    "jquery",
    "library"
  ],
  "dependencies": {
    "jquery": ">= 1.8.3"
  },
  "devDependencies": {
    "bootstrap": ">= 3.3.2",
    "highlightjs": "~8.4.0"
  }
}

```
upd. 'node_modules', not npm

**Comment by ck86** [comment]
I don't see what's wrong. You set the bower.json of bxslider as the one which should be handled by main-bower-files and it has only one dependency (jquery) which you get.

**Comment by amorphine** [comment]
I have to get all files listed in the 'main' section (not only jquery), do I?

**Comment by ck86** [comment]
then you have to set the config option `includeSelf` to `true`

**Comment by amorphine** [comment]
Thanks, I hope that works
