### ISSUE TITLE
Inverse group option doesn't seem to work

### ISSUE THREAD

**Issue by james-siteclick** [ck86/main-bower-files#150]
According to the docs it should be possible to match all bower files that are not in a certain group.

bower.json:

```
    "group": {
        "ie": ["css3pie", "REM-unit-polyfill"]
    }
```

gulpfile.js:

```
// Works
var ie8Files = mainBowerFiles({group: 'ie'});
// Fails
var bowerFiles = mainBowerFiles({ group: '!ie' });
```

The error is:
Error: group "!ie" does not exists in bower.json

**Comment by ck86** [comment]
Can't reproduce it. For me it works fine. What are the files do you get?

**Comment by james-siteclick** [comment]
Thanks for your reply.

I have resolved the "Error: group "!ie" does not exists in bower.json" error - I had an older version.

I have a slightly different issue now, which is that it doesn't seem to be possible to define modules in groups from dependencies.

Not sure if this is expected behaviour or a bug.

I have created an example test:
https://github.com/james-siteclick/mainbowerfilestest

In the bower.json, I have defined a group containing 'jquery'.  However 'jquery' does not appear in this group, perhaps because it is a sub-dependency.

Thanks again for your library :)

**Comment by ck86** [comment]
@james-siteclick you're right. the group option only handles your dependencies, not the sub-dependencies. you can "fix" it if you add jquery as a dependency of css3pie:

```json
"overrides": {
  "css3pie": {
    "main": "PIE.js",
    "dependencies": {
      "jquery": "*"
    }
  }
}
```

or you add jquery to your dependencies.
