### ISSUE TITLE
bowerFiles and more string paths in one gulp.src

### ISSUE THREAD

**Issue by aboalwi** [ck86/main-bower-files#152]
how can i do this: ?
`gulp.src([bowerFiles(bowerConf), "./app/js/**/*.js", "!./app/js/app.js"])`

i need it to use gulp-angular-modules which takes from: bower files and  js folder

it doesn't work since array in gulp.src accepts only strings, any way around it?

**Comment by ck86** [comment]
```js
var files = bowerFiles(bowerConf);

files.push("./app/js/**/*.js");
files.push("!./app/js/app.js");

return gulp.src(files);
```

**Comment by aboalwi** [comment]
Many thanks! :D
