### ISSUE TITLE
How exclude path?

### ISSUE THREAD

**Issue by olzhaskaliyev** [ck86/main-bower-files#155]
I tried to exclude fonts path of any vendors in my gulfiles.js in that way:
```
gulp.src(require('main-bower-files')(['**/*.{jpg,png,svg,gif,webp}', '!fonts/*'], function (err) {}))
    .pipe(gulp.dest('app/images'));
```
but it's not work. Is it possible exclude path of vendor, and if yes - how it's correct?

**Comment by ck86** [comment]
You can exclude paths through gulp.src:

```
var files = require('main-bower-files')('**/*.{jpg,png,svg,gif,webp}');

gulp.src([files, '!fonts/*'])
    .pipe(gulp.dest('app/images'));

**Comment by olzhaskaliyev** [comment]
Thx for quick answer, but this not work:
`Error: Missing positive glob`

**Comment by ck86** [comment]
Can you show me your example?
