### ISSUE TITLE
not include some dependencies

### ISSUE THREAD

**Issue by HASSANDL** [ck86/main-bower-files#157]
Hello, very very thanks.
I use your plugin but not include [oi.select](https://github.com/tamtakoe/oi.select) or [persian-date](https://github.com/babakhani/PersianDate) in mainbowerfiles.
both have bower.json.
my bower.json:
```javascript
"dependencies": {
    "ngCordova": "^0.1.27-alpha",
    "persian-date": "^0.1.8"
},
"devDependencies": {
    "oi.select": "^0.2.21"
}
```

**Comment by ck86** [comment]
There is an (includeDev)[https://github.com/ck86/main-bower-files#includedev] option and the main file of `persian-date` looks a bit weird ;)

**Comment by HASSANDL** [comment]
very very very thanks.
