### ISSUE TITLE
problem integrate bower and gulp

### ISSUE THREAD

**Issue by manvfx** [ck86/main-bower-files#161]
how to concat my custom code and bower files in build folder?

**Comment by ck86** [comment]
```js
var jsFiles = mainBowerFiles('**/*.js');

jsFiles.push('path/to/my/custom/js/files/**/*.js');

return gulp.src(jsFiles)
    //...
```

**Comment by manvfx** [comment]
Thanks a lot,
please check my file and Correction my code. please help me

[gulpfile.txt](https://github.com/ck86/main-bower-files/files/760008/gulpfile.txt)

**Comment by manvfx** [comment]
how to add multi file in argumant mainBowerFiles( js or css or fonts)

**Comment by ck86** [comment]
I am not here to fix your code.
