### ISSUE TITLE
Olways get EISDIR: illegal operation on a directory, read

### ISSUE THREAD

**Issue by cejixo3** [ck86/main-bower-files#163]
Example of task
var gulp = require("gulp");
var mainBowerFiles = require('gulp-main-bower-files');

gulp.task('bower', function() {
    return gulp.src('bower.json')
        .pipe(mainBowerFiles({}))
        .pipe(gulp.dest('./dst'));
});

**Comment by ck86** [comment]
your are using `gulp-main-bower-files` which is deprecated.

**Comment by cejixo3** [comment]
Thanks. I'll try to use main-bower-files
