### ISSUE TITLE
Invalid glob argument

### ISSUE THREAD

**Issue by iwfmp** [ck86/main-bower-files#164]
Sorry for the repetition, but I couldn't wrap my head around solving this.

This is my bower.json:
https://pastebin.com/aMxpS9if

This is my gulp task:
https://pastebin.com/LKfjtBYz

all in all seems pretty simple, right?
Still, it throws an invalid glob argument error.

**Comment by ck86** [comment]
what do you get if you do:

```js
console.log(mainBowerFiles('**/*.js'));
```

**Comment by iwfmp** [comment]
DestroyableTransform {
  _readableState:
   ReadableState {
     objectMode: true,
     highWaterMark: 16,
     buffer: BufferList { head: null, tail: null, length: 0 },
     length: 0,
     pipes: null,
     pipesCount: 0,
     flowing: null,
     ended: false,
     endEmitted: false,
     reading: false,
     sync: false,
     needReadable: true,
     emittedReadable: false,
     readableListening: false,
     resumeScheduled: false,
     defaultEncoding: 'utf8',
     ranOut: false,
     awaitDrain: 0,
     readingMore: false,
     decoder: null,
     encoding: null },
  readable: true,
  domain: null,
  _events:
   { end: { [Function: g] listener: [Function: onend] },
     prefinish: { [Function: g] listener: [Function] } },
  _eventsCount: 2,
  _maxListeners: undefined,
  _writableState:
   WritableState {
     objectMode: true,
     highWaterMark: 16,
     needDrain: false,
     ending: false,
     ended: false,
     finished: false,
     decodeStrings: true,
     defaultEncoding: 'utf8',
     length: 0,
     writing: false,
     corked: 0,
     sync: true,
     bufferProcessing: false,
     onwrite: [Function],
     writecb: null,
     writelen: 0,
     bufferedRequest: null,
     lastBufferedRequest: null,
     pendingcb: 0,
     prefinished: false,
     errorEmitted: false,
     bufferedRequestCount: 0,
     corkedRequestsFree: CorkedRequest { next: null, entry: null, finish: [Function] } },
  writable: true,
  allowHalfOpen: true,
  _transformState:
   TransformState {
     afterTransform: [Function],
     needTransform: false,
     transforming: false,
     writecb: null,
     writechunk: null,
     writeencoding: null },
  _destroyed: false,
  _transform: [Function] }

**Comment by TrySound** [comment]
@iwfmp I guess you use wrong package. It's not GULP-main-bower-files. It's just main-bower-files.

**Comment by iwfmp** [comment]
Jeez...Solved.
