### ISSUE TITLE
Please explain how to switch from gulp-bower-files

### ISSUE THREAD

**Issue by tigerclaw-az** [ck86/main-bower-files#29]
I was using the gulp-bower-files package and kept getting the message that it was deprecated and I should be using this package instead. Unfortunately it doesn't seem to just be a simple replacement of the 2. Can you please add some details to the README that explains how to switch from gulp-bower-files to main-bower-files?

Here is a task I'm using with the gulp-bower-files:

```
gulp.task('fonts', function () {
    var streamqueue = require('streamqueue');
    return streamqueue({objectMode: true},
        $.bowerFiles(),
        gulp.src(['app/fonts/**/*', 'bower_components/foundation-icon-fonts/**/*'])
    )
        .pipe($.filter('**/*.{eot,svg,ttf,woff}'))
        .pipe($.flatten())
        .pipe(gulp.dest('dist/fonts'))
        .pipe($.size());
});
```

**Comment by Mahmoudz** [comment]
try out 

```js
gulp.plugins = require('gulp-load-plugins')({
    pattern: ['gulp-*', 'main-bower-files']
});
```
