### ISSUE TITLE
CSS file in a bower package is ignored.

### ISSUE THREAD

**Issue by ciuncan** [ck86/main-bower-files#43]
My gulpfile is configured to inject the css and js references into the index.html file. But i observed that the css file of angular-ui-grid package is not injected.

When i put a `console.log(mainBowerFiles())` into the vendors task function in my gulpfile.js, following is sent to output:

```
[ 'bower_components/angular/angular.js',
  'bower_components/angular-animate/angular-animate.js',
  'bower_components/angular-route/angular-route.js',
  'bower_components/angular-aria/angular-aria.js',
  'bower_components/hammerjs/hammer.js',
  'bower_components/angular-ui-grid/ui-grid.js',
  'bower_components/angular-material/angular-material.js',
  'bower_components/angular-material/angular-material.css' ]
```

I couldn't find out why `angular-material.css` is available, but `ui-grid.css` is not, even though all conditions (file existance, file types, mimetypes, encoding etc.) are same for those two packages.

Here is my bower.json:

```
{
  "name": "userinterface",
  "main": [
    "/dist/userinterface.min.js",
    "/dist/userinterface.min.css"
  ],
  "version": "0.1.1",
  "description": "TODO",
  "authors": [
    "TODO"
  ],
  "ignore": [
    "**/.*",
    "package.json",
    "klei.json",
    "gulpfile.js",
    "node_modules",
    "bower_components",
    "src"
  ],
  "dependencies": {
    "angular": "1.3.1",
    "angular-animate": "1.3.1",
    "angular-route": "1.3.1",
    "angular-aria": "1.3.1",
    "angular-material": "~0.4.2",
    "angular-ui-grid": "~3.0.0-rc.12"
  },
  "devDependencies": {
    "angular-mocks": "1.3.1"
  },
  "resolutions": {
    "angular-animate": "1.3.1",
    "angular-aria": "1.3.1",
    "angular": "1.3.1"
  }
```

**Comment by douglas-treadwell** [comment]
Specifically, in your bower.json you need:

  "overrides": {
    "angular-ui-grid": {
      "main": [
        "./ui-grid.css",
        "./ui-grid.eot",
        "./ui-grid.js",
        "./ui-grid.svg",
        "./ui-grid.ttf",
        "./ui-grid.woff"
      ]
    }
}

I was very surprised to find that ui-grid did not provide a spec-conforming bower file.
