### ISSUE TITLE
lunr.js throwing Error: EISDIR, open due to dot in package name

### ISSUE THREAD

**Issue by Soviut** [ck86/main-bower-files#48]
```Error: EISDIR, open '/Users/me/project/frontend/dist/local/bower_components/lunr.js'```

lunr.js package isn't copying to my dist folder because it's got a dot in the folder name. This seems to be treating it as if it's a file when it tries to copy.

**Comment by ck86** [comment]
Please re-open it if you still have this issue and can explain how to reproduce it. thanks!
