### ISSUE TITLE
Incorrect path replacing in files structure with subfolder

### ISSUE THREAD

**Issue by uoziod** [ck86/main-bower-files#56]
Basically main-bower-files works just fine! Thank you guys!

But I've met a buggy situation. Lets say we have installed **fontawesome** bower component. Apart from CSS-files we have also font-files there that was copied, and it's good. But they were located in separate folder then CSS.

So, in resulting CSS-file we have removed **bower_components**, that's good, and mentioned files are also located there, but reference in CSS-file is still:

``` css
src: url('../fonts/fontawesome-webfont.eot?v=4.2.0');
```

**Comment by cosven** [comment]
hello, I also have a problem in path.
I want to concat all the css file in `vendor(bower)` to a single one. like `all.min.css`
I know how to get a **un**flat structure in collecting the vendor files. However, once I concat all the css files, it will equal to a flat structure ... q.q

**Comment by ck86** [comment]
I don't get it. Can you share code examples?

**Comment by cosven** [comment]
This is the my project files structure
![image](https://cloud.githubusercontent.com/assets/4962134/10512703/f8dea0cc-7374-11e5-94ba-cc50480936a2.png)

First, 
```js
gulp.task('vendor', function(){
     // css collections
     gulp.src(mainBowerFiles(), {base: "vendor"})
            .pipe(gulp.dest("./dist"));

gulp.src('dist' + '/**/*.css', {base: '.'})
       .pipe(concat('all.css'))
       .pipe(minifyCss({relativeTo: '..'}))
       .pipe(rename('all.min.css'))
       .pipe(gulp.dest('./public'));
 });
```
Until now, I have one single file in `public` directory.
![image](https://cloud.githubusercontent.com/assets/4962134/10512840/dc14a4fe-7375-11e5-9f5c-48d32bacb3ca.png)

So, problem comes, `src: url('../fonts/fontawesome-webfont.eot?v=4.2.0');` font files are unreachable.

**Comment by ck86** [comment]
Sure, because the fontawesome css file assumes the fonts at a relative to location to its css file, that is not a problem of main-bower-files. If you would move your all.min.css to something like public/css it would work.

**Comment by cosven** [comment]
I know that move `all.min.css` to `public/css` that can make it working.
But `../font` is just an example, 
there maybe code like this `src: url('../../images/hello.png')`

**Comment by ck86** [comment]
I know, but this is not related to main-bower-files. It just gives a list of files, what you are doing with those files is up to you.

**Comment by cosven** [comment]
ok, thanks ~
