### ISSUE TITLE
mainBowerFiles() return a empty array in Windows

### ISSUE THREAD

**Issue by zongwei007** [ck86/main-bower-files#61]
I use debugging option, the console output like this:

```console
PackageCollection add            jquery e:\Documents\FrontEndWorkspace\React\bower_components\jquery
PackageCollection add            backbone e:\Documents\FrontEndWorkspace\React\bower_components\backbone
PackageCollection add            jquery-ie8 e:\Documents\FrontEndWorkspace\React\bower_components\jquery-ie8
PackageCollection add            fontawesome e:\Documents\FrontEndWorkspace\React\bower_components\fontawesome
Package          overriding dependencies         fontawesome {}
PackageCollection add            bootstrap e:\Documents\FrontEndWorkspace\React\bower_components\bootstrap
Package          overriding dependencies         bootstrap {"jquery":">= 1.9.1"}
PackageCollection add            es5-shim e:\Documents\FrontEndWorkspace\React\bower_components\es5-shim
PackageCollection add            react e:\Documents\FrontEndWorkspace\React\bower_components\react
```

I try to track the code, found that problem in `\lib\package_collection.js` (line 55):
```javascript
if (path.indexOf(this.opts.paths.bowerDirectory) === -1) {
```
In my Windows, the value of `bowerDirectory` is like to `E:\Documents\FrontEndWorkspace\React\bower_components` :sweat:

So I modify the code in `index.js`, it work well now.
```javascript
opts.paths = {
        bowerJson: bowerJson,
        //bowerDirectory: bowerDirectory
        bowerDirectory: path.normalize(bowerDirectory)
    };
```

**Comment by ck86** [comment]
Can you update to v2.4.2? It could be the hardcoded path separator which I have changed to path.sep.

**Comment by zongwei007** [comment]
In my opinion, it is without reference to path.sep. In my environment, when code run to `if (path.indexOf(this.opts.paths.bowerDirectory) === -1) {`,

then the value of path is: 
`e:\Documents\FrontEndWorkspace\React\bower_components\bootstrap` 
and the value of bowerDirectory is 
`E:\Documents\FrontEndWorkspace\React\bower_components`.

It makes `indexOf` return a `false` value. I think is not the expected results.

**Comment by ck86** [comment]
This check is necessary for the `includeSelf` option, but I can not reproduce that lowercase / uppercase problem. Can you figure it out?

**Comment by zongwei007** [comment]
I found the reason. It because of I use nodejs version of 0.11.x.
https://github.com/joyent/node/issues/7880

I install nodejs 0.10.35,  the drive letter change to upper case and it's ok.
