### ISSUE TITLE
Can't declare destination directory for files in bower.json (like grunt-bower)

### ISSUE THREAD

**Issue by cherrydev** [ck86/main-bower-files#62]
One of the most useful features of grunt-bower is its ability to specify the destination directory alongside the source name/glob in its exportsOverride configuration section of bower.json.

For reference, this looks like: 
```
"exportsOverride": {
        "bootstrap": {
            "js": "dist/js/*.*",
            "css": "dist/css/*.*",
            "fonts": "dist/fonts/*.*"
        },
        ...etc
```

Without this functionality, all you're left with from the pipe that main-bower-files returns is the original paths of the files, but without any of the context of what bower package it belonged to.  I understand, though, that one of the benefits of gulp is the separation between src() and dest(), so the functionality might not be possible to implement while just returning a pipe from the task.

**Comment by ck86** [comment]
`grunt-bower` is a task to copy bower files to specified destination paths, but `main-bower-files` is just a module to retrieve all main files.
It is up to you what you want to do (copying, concatenating, uglifying, etc.).

**Comment by cherrydev** [comment]
Yes, I understand precisely what main-bower-files is designed to do and I understand that grunt-bower actually does several loosely-related tasks all together, which goes against the design principals of gulp. While it would be possible to end up with the same layout using main-bower-files and grunt-bower's export functionality, you would end up with a lot of repetition if you wanted to replicate some scenarios that grunt-bower makes simple, and I thought I'd start trying to solve the problem by working with the gulp task that already does MOST of what I need.  To be specific, a (presumably) common scenario for laying out one's front-end files would be the one that I posted above.
To replicate this using main-bower-files, you would have to first write, in your bower.json:
```
overrides {
	bootstrap {
		main: [
			"dist/js/*.*",
            "dist/css/*.*",
            "dist/fonts/*.*"
		]
	},
	jquery {
		main: "jquery.{js,min.js,min.map}"
	}
	... etc
}
```
You would then be returned a pipe that contains, basically:
```
[
"bower_components/bootstrap/dist/js/bootstrap.js",
"bower_components/bootstrap/dist/js/bootstrap.min.js",
"bower_components/bootstrap/dist/css/bootstrap.css",
etc...
"bower_components/jquery/jquery.js",
etc...
]
```

As you can see, you've now lost the context of which bower component each src file belongs to unless you had code that split the files back up into their separate components by examining the path of each file and re-categorizing it according to its source path.  Once that was done, another set of configuration data would need to be read that would map the different files within each bower component into different destination directories.  As you can hopefully see, being able to tag each file (or file glob) with some sort of destination "hint" is much more expressive than just returning a list of files (even though I believe it's possible to determine which glob matched which file).  While it may seem that it would be trivial to achieve the same effect as the above example simply by splitting the src files up by their file extension, I'll point out that even in the above example, that would fail to be a robust solution: bootstrap's "fonts" directory contains a number of file types, one of them an .svg file.  It would be common to have .svg files that had other purposes other than a font and therefor would be appropriate to be separated into a different destination directory.

All in all, what I'm asking is: can you see a simple way that the "overrides" configuration could express some sort of categorization tag for each component of each bower package's "main" override and then make that information available in the pipe?

For example:

```
	main [
		{ "src" : "dist/js/*.*", "tag" : "js" },
		{ "src" : "dist/css/*.*", "tag" : "css" },
		etc...
	]
```

I understand that main-bower-files just returns a list of file names, so it may not be possible to add this sort of functionality without making major changes to it that would be out of scope for what you're trying to accomplish.

**Comment by cherrydev** [comment]
So, looking through your source code, it looks like if Package could understand the enhanced override configuration and collect the tag associated with each file (while assigning an empty tag to non-overriden files, or overridden files that use the existing string pattern), PackageCollection could just run a supplied callback for each file after running the filter, letting the developer do whatever they want with it:

```
function cb(filename, bowerPackage, tag) {
    // Create your own structures to pass to src and dest based on the packages and tags
    ...
}

mainBowerFiles( { callback: cb } );
``` 

If you are interested in having this functionality in main-bower-files, let me know and I'll try to work on a pull request for it.  If not, I'll just continue the method I'm using (using gulp-grunt with grunt-bower, sadly).

**Comment by ck86** [comment]
At [feature/gulp-stream-with-tags](https://github.com/ck86/main-bower-files/tree/feature/gulp-stream-with-tags) I've added a stream function which returns a vinyl-fs stream (like gulp.src) where the file objects have two more properties: `package` and `tag`.

To tag the files, I've added an option `tag` instead of another bower.json property.
```js
mainBowerFiles.stream({
  tags: {
    packageName: {
      '**/*.js': 'js',
      '**/*.css': 'css',
    }
  }
});
```

What do you think?

**Comment by ck86** [comment]
@cherrydev did you have had a look on it?

**Comment by ck86** [comment]
If you have still interest in this feature, you have the possibility to re-open this issue.

**Comment by alexanderkatkov** [comment]
Hi, interesting issue.
I have same issue.
I'm using gulp.
I need to take main files from bower components folder & copy each file to unique folder.
Example:
We have jquery.min.js, normalize.css, remodal.min.js, remodal.css, remodal.theme.css in bower components as main files.
I need to copy jquery to demo/js folder. remodal.js to js/components/remodal folder, normalize.css to less/components/normalize folder and all remodal css to less/components/remodal folder.
Is it posible somehow to assign destination folder to each file?
Thanks for responce.

**Comment by TrySound** [comment]
@alexanderkatkov It's not main-bower-files issue. You need to look at streams and change path and base of files.
