### ISSUE TITLE
Look for index.js if main isn't given

### ISSUE THREAD

**Issue by adam-lynch** [ck86/main-bower-files#63]
Unless I'm missing an obvious reason why this shouldn't happen.

Example package: https://github.com/darsain/tooltips (installing from GitHub).

**Comment by TrySound** [comment]
Besause this index.js is not compiled and will not work in the browser.

**Comment by adam-lynch** [comment]
@TrySound, I was just debugging that right now :smile:. 

In this case, the file is designed for the web but it is assumed there are dependencies already included. The maintainer would have to add a `bower.json` with the dependencies listed.

I'm still not 100% sure this is a stupid idea (although I'm leaning there since most node projects will have an `index.js` at the root which won't work) so I'll leave it up to you @ck86 to close.

**Comment by ck86** [comment]
The problem here is that not all bower packages are actual javascript projects.
You can define a default [main as an option](https://github.com/ck86/main-bower-files#main-1).

**Comment by adam-lynch** [comment]
Ah didn't know of the main option. Thanks.
