### ISSUE TITLE
 SCSS issue

### ISSUE THREAD

**Issue by volodymyrl** [ck86/main-bower-files#64]
I use main-bower-files with gulp to concat all vendors into one file, and got an error when I tried to convert SCSS to CSS.

https://github.com/volodymyrl/starter/blob/master/gulpfile.js#L119-L138

stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
Error: file to import not found or unreadable: susy/language/susy
Current dir: D:/projects/starter/app/styles/vendors/

Do you know were can be the problem? Thanks!

**Comment by TrySound** [comment]
I recommend you to filter by bower and use for js or any other something like this:
```
gulp.src(bower('**/*.js').concat([
  src/js/**/*.js
]))
```
The code will be clearer.

**Comment by ck86** [comment]
@volodymyrl when you concat scss files, you should remove the @import statements.

**Comment by volodymyrl** [comment]
Thanks for your answer @ck86 but what do you meen by the "remove" ? I can't edit bower vedors files

**Comment by ck86** [comment]
You could use for example [gulp-replace](https://www.npmjs.com/package/gulp-replace) or filtering out the scss files and use `includePaths` options of node-sass.
