### ISSUE TITLE
Using Filter to get JS/CSS files only

### ISSUE THREAD

**Issue by codeofsumit** [ck86/main-bower-files#67]
I'm trying to get all the main bower files, separate them into JS, CSS and Fonts and put them into their designated folders but I'm having some problems with it.

this code will put all the files into the folder `dist/js/libs`
```
gulp.task('handleBowerFiles', function() {
    return gulp.src(mainBowerFiles())
        .pipe(gulp.dest('dist/js/libs'))
		.pipe(notify({ message: 'Bower task complete' }));
});
```

Now I would like to only get JS files and put them into that same folder but this doesn't seem to work
```
[...]
return gulp.src(mainBowerFiles([['*.js']]))
[...]
```

Could you tell me how to properly filter the files? 

The readme says it's done ilke this: `mainBowerFiles([[filter, ]options])`

but using it like that throws an error:

```
gulp.task('handleBowerFiles', function() {
    return gulp.src(mainBowerFiles([['*.js'], {
		checkExistence: true
	}]))
        .pipe(gulp.dest('dist/js/libs'))
		.pipe(notify({ message: 'Bower task complete' }));
});
```

What am I doing wrong?

**Comment by TrySound** [comment]
use `**/*.js` because paths don't flatten.

**Comment by TrySound** [comment]
It's could be used without array, just a string.

**Comment by codeofsumit** [comment]
alright thanks, this is working for me

```
gulp.task('handleBowerFiles', function() {
	// move JS files
    gulp.src(mainBowerFiles([['**/*.js']]))
        .pipe(gulp.dest('dist/js/libs'))
		.pipe(notify({ message: 'Bower task complete' }));
	
	// move CSS files
	gulp.src(mainBowerFiles([['**/*.css']]))
        .pipe(gulp.dest('dist/css/libs'))
		.pipe(notify({ message: 'Bower task complete' }));
	
	// move font files
	gulp.src(mainBowerFiles(['**/fontawesome**']))
        .pipe(gulp.dest('dist/fonts'))
		.pipe(notify({ message: 'Bower task complete' }));
});
```

anything that could be done better/more efficient?

**Comment by ck86** [comment]
It is not necessary to use an array filter, just use the string, e.g.:
```js
mainBowerFiles('**/*.js')
```

**Comment by codeofsumit** [comment]
changed it, thanks!
