### ISSUE TITLE
Get paths instead?

### ISSUE THREAD

**Issue by ethanclevenger91** [ck86/main-bower-files#68]
I'd like to use this plugin to pass the paths to the main sass files for my various bower packages into the sass plugin. Right now the plugin returns the files themselves. Is there a way the plugin could return an array of paths to the containing directory instead of files via an option, or is there another method by which I can replace the array of files I get as a result with their corresponding paths?

So instead of `.../bootstrap-sass-official/assets/stylesheets/_bootstrap.scss` I just need `...../bootstrap-sass-official/assets/stylesheets`. Let me know if this would be more appropriate on StackOverflow - I just thought perhaps this would be a useful feature if it didn't already exist.

**Comment by ck86** [comment]
That's too specific, but here is an example:

```js
var path = require('path');
var includePaths = mainBowerFiles('**/*.{scss,sass}').map(function(file) {
  return path.dirname(file);
});
```

**Comment by ethanclevenger91** [comment]
Ah, I was unaware of path built into Node, that's exactly what I needed. 
Gulp is about all I currently do in Node. Thanks for the tip!

**Comment by ck86** [comment]
You are welcome ;)
