### ISSUE TITLE
Control order of packages

### ISSUE THREAD

**Issue by benfoster** [ck86/main-bower-files#74]
I need to ensure that jQuery is loaded before AngularJS. Since the Angular bower package does not actually have a dependency on jQuery it is included in my bundle first (I guess it falls back to alphabetical).

Is this possible?

**Comment by ayakovlevgh** [comment]
https://github.com/ck86/main-bower-files/issues/4

**Comment by ck86** [comment]
You can add jQuery as an angular dependency in your own bower.json file:

```json
{
    "overrides": {
        "angular": {
            "dependencies": {
                "jquery": "*"
            }
        }
    }
}
```

**Comment by warapitiya** [comment]
It's great if you could explain more or provide us a example?
