### ISSUE TITLE
Does not find any css in main object

### ISSUE THREAD

**Issue by beckend** [ck86/main-bower-files#76]
Bower mediaelement: 
"main": [
      "./build/mediaelement-and-player.js",
      "./build/mediaelementplayer.css" 
]

animate.css:
"main": "./animate.css"

module returns no files, not even the js.

**Comment by TrySound** [comment]
@beckend use this globule in filter `**/*.css` because the path is relative to current directory (bower_components/plugin_name/build/mediaelementplayer.css)

**Comment by beckend** [comment]
Actually I'm sorry about this, but the animate.css and mediaelement was installed as --save-dev, this plugin checks by default only for normal deps. I added them as normal dependency to make it work.

**Comment by ck86** [comment]
@beckend you can use the [includeDev](https://github.com/ck86/main-bower-files#includedev) option.

**Comment by beckend** [comment]
Scrolled too fast, thanks - it works excellent.
