### ISSUE TITLE
CSS files

### ISSUE THREAD

**Issue by danielbsig** [ck86/main-bower-files#78]
What exactly would be needed to process CSS files and/or other files provided by bower components? Is it supported?

**Comment by TrySound** [comment]
@danielbsig gulp and it plugins.
```js
gulp.src(bower('**/*.css'))
       .pipe(concat('bundle.css'))
       .pipe(gulp.dest('dist/css'));
```

**Comment by danielbsig** [comment]
Great, thanks!

**Comment by NeXTs** [comment]
@TrySound @danielbsig 
Hi! This solution may fetch a lot of redundant styles. How to concat ONLY css files from **main**?

**Comment by ck86** [comment]
@NeXTs there should only included main css files?

**Comment by NeXTs** [comment]
Yes, I am sorry. I did not notice "bower(...)" part. That works great. Thank you.
Also found [this solution](https://github.com/ck86/main-bower-files/issues/67#issuecomment-75447830)

**Comment by TrySound** [comment]
@NeXTs It's not solution. It's problem. Task should do only one task.

**Comment by NeXTs** [comment]
@TrySound sure. it was a misunderstanding.
