### ISSUE TITLE
return empty array if bower.json doesn't exists

### ISSUE THREAD

**Issue by TrySound** [ck86/main-bower-files#79]

**Comment by TrySound** [comment]
I suggest you to get callback from options on errors and call it, but not throw an errors. It could make building more flexible for optional situation. You may throw error when callback not passed.

**Comment by TrySound** [comment]
```js
// Default
{
  error: true // Boolean || Function
}
```

**Comment by ck86** [comment]
What about try..catch? There is no async stuff.

**Comment by TrySound** [comment]
@ck86 Maybe, but exceptions is one of the most slower things in js.

**Comment by TrySound** [comment]
@ck86 And I want to use it without wrappings out of the box.

**Comment by ck86** [comment]
OK, I am open for pull requests, because I have currently not much time.

**Comment by TrySound** [comment]
@ck86 Why check existing of bower.json twice in `index.js` and `package_collection.js`?

**Comment by ck86** [comment]
Good question, I think it could be removed at `package_collection.js`.

Probably I have added it for some reasons, I don't know anymore. :laughing:
