### ISSUE TITLE
the "ignore" option redefines the meaning of a bower option with the same name

### ISSUE THREAD

**Issue by hanifbbz** [ck86/main-bower-files#80]
This causes confusion. This plugin expects "ignore" to be a boolean that excludes the whole package from the process, but in bower, "ignore" is an array of strings and is used to exclude individual files from the process: https://github.com/bower/bower.json-spec#ignore

ps. in the test files `ignore` seems to be an object: https://github.com/ck86/main-bower-files/blob/master/test/_bower.json#L15

**Comment by ck86** [comment]
You are right, but this option is used by bower on install and has no effect after that.

**Comment by hanifbbz** [comment]
But we don't know if in the future they may need to use it for something after install.

**Comment by ck86** [comment]
If they change it, I will change it too ;)
