### ISSUE TITLE
Add error to output if .bowerrc is empty

### ISSUE THREAD

**Issue by sirhodes** [ck86/main-bower-files#83]
I ran into this issue [question & self-answer here](http://stackoverflow.com/questions/29979990/syntaxerror-unexpected-end-of-input-error-using-gulp-and-main-bower-files-packa).
I feel as though it could beneficial to the user to make the package somewhat verbose in outputting an error if the user's .bowerrc file is empty, which is an understandable mistake. Maybe after parsing the JSON in .bowerrc, if !length, then output a more user-friendly error. I could even make this contribution via a fork and pull request, if the repo owner feels as though it's a worthwhile contribution.

**Comment by ck86** [comment]
It is not common to have an empty .bowerrc file, just your mistake?

**Comment by TrySound** [comment]
@sirhodes It must contain at least empty object.
