### ISSUE TITLE
'ignore' does nothing

### ISSUE THREAD

**Issue by jshado1** [ck86/main-bower-files#84]
```js
gulp.task('bowerFiles', function() {
    var options = {
            debugging: true,
            overrides: {
                'angular-mock': {
                    ignore: true
                },
                'bootstrap-sass': {
                    ignore: true
                },
                'jquery': {
                    ignore: true
                }
            }
        };
    if ( isTesting ) {
        options.overrides['angular-mock'].ignore = false;
    }

    return gulp
        .src( mainBowerFiles( options ) )
        .pipe( plugins.rename('vendor.js') )
        .pipe( gulp.dest( BUILD_DEST ) );
});
```
```sh
…
PackageCollection add		 bootstrap-sass […]/bower_components/bootstrap-sass
Package		 overriding main	 bootstrap-sass ["assets/stylesheets/_bootstrap.scss","assets/fonts/bootstrap/glyphicons-halflings-regular.eot","assets/fonts/bootstrap/glyphicons-halflings-regular.svg","assets/fonts/bootstrap/glyphicons-halflings-regular.ttf","assets/fonts/bootstrap/glyphicons-halflings-regular.woff","assets/fonts/bootstrap/glyphicons-halflings-regular.woff2","assets/javascripts/bootstrap.js"]
Package		 overriding dependencies	 bootstrap-sass {"jquery":">= 1.9.0"}
PackageCollection add		 jquery […]/bower_components/jquery
…
```

**Comment by ck86** [comment]
Hey @jshado1, 
the `overrides` is part of the bower.json. You can override the main property environment based, see https://github.com/ck86/main-bower-files#main

**Comment by jshado1** [comment]
Hiya, thanks for your response.

> These options **can** be set directly in your bower.json file, e.g.:

(emphasis added)

_Can_ is a choice. This should be changed to _are_:

> These options are set directly in your bower.json file, e.g.:

**Comment by jshado1** [comment]
Also, I don't think this belongs in `bower.json` because it limits what can be done. Ex I can't conditionally set an ignore in a json file.

**Comment by ck86** [comment]
you can "ignore" the package if you don't specify any main files, e.g.:

```json
{
    "overrides": {
        "angular-mock": {
            "main": {
                "production": {},
                "testing": ["path/to/file"]
            }
        }
    }
}
```

**Comment by raptor235** [comment]
I tend to agree that putting the ignore only in bower.json is limiting... we have one gulp build process that has to build three types of builds with various bower components per build... is the expectation to then have 3 different bower files?

**Comment by ck86** [comment]
Yes it would be the best solution for this purpose.

**Comment by Kratos-SA** [comment]
I am running into the same problem where its adding sass to it. Please help


```
"overrides":
{
	"font-awesome":
	{
           "main": {"production": {}},
		"ignore":true
	}
}
```

**Comment by ck86** [comment]
@Kratos-SA can you log the value of process.env.NODE_ENV?

**Comment by Kratos-SA** [comment]
I got it to work thanks.
