### ISSUE TITLE
Files are not included when bower.json "main" has slash prefix

### ISSUE THREAD

**Issue by darklow** [ck86/main-bower-files#85]
.JS and .CSS files are not included when `bower.json` has following format:

```
  "main": [
    "/epoch.min.js",
    "/epoch.min.css"
  ],
```

For example this library has following bower.json format:
https://github.com/fastly/epoch/blob/master/bower.json

If i remove slashes, then files are included.

Any workarounds maybe?
Using gulp build with `gulp-load-plugins`:
```
var $ = require('gulp-load-plugins')({
  pattern: ['gulp-*', 'main-bower-files']
});
```

Thank you.

**Comment by ck86** [comment]
I think it's an issue of the epoch package, because a path with a starting slash is an absolute path.
