### ISSUE TITLE
Getting all but one or only one

### ISSUE THREAD

**Issue by adam-lynch** [ck86/main-bower-files#87]
What would you suggest to do in this scenario? I need to load one bower module separately. So ideally I'd like to use main-bower-files to give me all of my bower modules' (and their dependencies') main files *except* module X's and its dependencies' main files unless those dependencies are needed by another bower module too. And I'd like to separately ask main-bower-files just for the main bower files of module X (and its dependencies). 

Then I could have two gulp tasks to have two javascript files in the end. One for module X and one for the rest.

Right now what I'm going to have to settle for is manually referencing the main files needed for module X and for the other task I'll just have to use the filter option but this means that dependencies of module X will still go into both resultant files.

**Comment by ck86** [comment]
You can have 2 bower projects inside of your own project. The directory structure could look like:

/package-a
/package-a/bower.json
/package-a/bower_components/*
/package-b
/package-b/bower.json
/package-b/bower_components/*

Now you can use `main-bower-files` with `paths` option:

```js
var packageAFiles = mainBowerFiles({
  paths: {
    bowerJson: './package-a/bower.json'
  }
});

var packageBFiles = mainBowerFiles({
  paths: {
    bowerJson: './package-b/bower.json'
  }
});
```

**Comment by TrySound** [comment]
@ck86 Can you add this recipe in documentation, because it's not obvious.

**Comment by adam-lynch** [comment]
I do already have one `bower.json` and 3 `package.json`'s though haha. I guess I could use module X's own `package.json` with `includeSelf` instead of two main ones but then your way is more future proof if I need more than just module X.

**Comment by nathanaelnsmith** [comment]
I think the solution for issue #138 can also solve this.
