### ISSUE TITLE
Returns Empty Array

### ISSUE THREAD

**Issue by doostinharrell** [ck86/main-bower-files#89]
When defining and running a gulp task main-bower-files is returning an empty array.  I have published my code to a repo if you have a chance to take a look.

https://github.com/doostinharrell/issues-with-bower

**Comment by ck86** [comment]
Hi @doostinharrell,

The bower package `modernizr-min` has no main file defined, you need to override it in your own bower.json, see [here] (https://github.com/ck86/main-bower-files#main).

**Comment by doostinharrell** [comment]
Hi @ck86,

Thanks for the feedback. I installed a few additional libraries that have a main file defined and my array is still empty.  Nothing is piping to my js destination.  I updated my repo (https://github.com/doostinharrell/issues-with-bower).  Have I mis-configured something?  

Any assistance you can provide would be greatly appreciated!

Thanks!

**Comment by ck86** [comment]
Yes. You have to set the option `includeDev` to `true`.

**Comment by doostinharrell** [comment]
Awesome!  That worked.
Thank you so much for your help.

**Comment by ck86** [comment]
No problem.
