### ISSUE TITLE
Some bower packages are not included in automated build

### ISSUE THREAD

**Issue by dgrubelic** [ck86/main-bower-files#90]
Hi there,

i have a gulp driven build where i want to get all main .js file files from bower components, concat them and save them as one libraries.js file (the same thing i want to do with .css files).
Unfortunately, some bower packages are not included:
* moment.js - https://github.com/moment/moment
* boostrap-daterangepicker - https://github.com/dangrossman/bootstrap-daterangepicker

Any reason why is this happening? Is there any way to automatically include these files into the build?

**Comment by ck86** [comment]
Can you share your bower.json and gulpfile?

**Comment by dgrubelic** [comment]
I solved the problem with moment.js missing. Turn out that one of libs that require moment.js wasn't included in bower as a dependency. I still have problem with angular-bootstrap-select & bootstrap-daterangepicker.

Looks like angular-bootstrap-select deps are not included.

Here's the bower.json file:

```javascript
{
  "name": "some name - removed on purpose",
  "version": "0.0.1",
  "authors": [],
  "description": "---",
  "main": "index.js",
  "moduleType": [
    "globals"
  ],
  "keywords": [],
  "license": "MIT",
  "ignore": [
    "**/.*",
    "node_modules",
    "bower_components",
    "test",
    "tests"
  ],
  "dependencies": {
    "angular": "~1.3.15",
    "angular-bootstrap": "~0.12.1",
    "angular-sanitize": "~1.3.15",
    "angular-touch": "~1.3.15",
    "angular-ui-router": "~0.2.13",
    "restangular": "~1.5.1",
    "bootstrap": "~3.3.4",
    "enquire": "~2.1.2",
    "angular-bootstrap-select": "v0.1.0-rc2",
    "angular-growl-v2": "~0.7.3",
    "angular-animate": "~1.3.15",
    "ng-file-upload": "~4.0.3",
    "bootstrap-daterangepicker": "~1.3.21"
  }
}
```

and gulp task doing all the work:

```javascript
var gulp    = require('gulp'),
    concat  = require('gulp-concat'),
    bowerFiles = require('main-bower-files');

gulp.task('libraries', function () {
  gulp.src(bowerFiles(['**/*.js', '*.js'], {
    debugging: true
  }))
    .pipe(concat('libraries.min.js'))
    .pipe(gulp.dest('./public/js/vendor/'));
});
```

**Comment by ck86** [comment]
I can't reproduce your issue. If I remove the concat and see what files are copied, then I can see that angular-bootstrap-select.js and daterangepicker.js are also copied.

**Comment by dgrubelic** [comment]
Seems like that.. But for some reason errors are thrown with those two issues. Looks like your lib did it's job. Sorry for opening an issue. :)
