### ISSUE TITLE
unexpected output when using with gulp and npm as dependent manager

### ISSUE THREAD

**Issue by liyuan-rey** [ck86/main-bower-files#94]
hello guy,
nice done with main-bower-files!
but i met an issue with this tool, my project uses jquery(npm managed, not bower), please check these codes:
```javascript
var mainBowerFiles = require('main-bower-files');
var mydebug = require('gulp-debug');
gulp.task('prepare-vendor-files', function() {
    return gulp.src(
        mainBowerFiles({
            paths: {
                bowerDirectory: './node_modules',
                bowerrc: '',
                bowerJson: './package.json'
            },
            checkExistence: true
            ,debugging: true
        }),
        {
            base: './node_components'
        })
        .pipe(gulp.dest('./build/vendor'))
        .pipe(mydebug({ title: 'gulp-debug:', minimal: false}));
});
```
wish i could get 
'./build/vendor/jquery/dist/jquery.js',  but instead
'./build/node_modules/jquery/dist/jquery.js' found.

i have no idea whether it is a bug or not, please help.

**Comment by ck86** [comment]
Hey @liyuan-rey you base option is wrong, it should be `./'node_modules'.

**Comment by liyuan-rey** [comment]
omg...such a stupid question that i've asked... @.@
thanks anyway~
