### ISSUE TITLE
Return array contains absolute paths

### ISSUE THREAD

**Issue by DaRamirezSoto** [ck86/main-bower-files#97]
Documentation states

> mainBowerFiles returns an array of files where each file is a relative path without any globs (** or *).

But I am getting an array with absolute paths.

**Comment by TrySound** [comment]
@DaRamirezSoto Small misunderstanding.
Globs are relative, but returns absolute paths. You can map your result and use `path.relative` to get what you want.

**Comment by TrySound** [comment]
@DaRamirezSoto Noop, there are absolute too.
@ck86 Give me access, please.

**Comment by DaRamirezSoto** [comment]
@TrySound  thnx, I was bedazzled as  why this had gone unnoticed.
At least I can stop trying to make it to work properly, 
I added absolute path to base for now as work around until there is a fix.

**Comment by ck86** [comment]
@DaRamirezSoto you are right that mainBowerFiles returns absolute paths, but in that context it is irrelevant, because without any asterisks gulp will flatten the result.

**Comment by DaRamirezSoto** [comment]
@ck86 I am not really sure if I understand what you mean by this.
I've been using it with absolute paths and is fine like this.
Maybe just change the docs in this case ?

**Comment by ck86** [comment]
Yes, it's just outdated.
